site_name: Курс по нейросетям
site_url: https://example.com/
nav:
  - Home: index.md
  - About: about.md
  - Torch-grad: Torch-grad.md
  - Torch-optim: Torch-optim.md
  - Dataloader: Dataloader.md
  - VAE: VAE.md
theme: readthedocs
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
       - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  #material
  #readthedocs